---
- name: Install dependencies
  hosts: localhost
  remote_user: root

  tasks:
    - name: Install lazyvim
      git:
        repo: https://github.com/LazyVim/starter
        dest: ~/.config/nvim
    
    - name: Remove .git folder from .config/nvim
      command: rm -rf ~/.config/nvim/.git

