#!/bin/bash

export XDG_CONFIG_HOME="$HOME"/.config

# Download .zshrc from main dotfiles repo
curl -o "$HOME/.zshrc" https://raw.githubusercontent.com/Lucioschenkel/dotfiles/main/.zshrc

# Setup homebrew
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.zshrc

# Install brew packages
/home/linuxbrew/.linuxbrew/bin/brew bundle install --file Brewfile

# Symlink dotfiles
stow .

# Setup shell completion
midir -p "$HOME/.zfunc"
flux completion zsh >$HOME/.zfunc/_flux
kubectl completion zsh >$HOME/.zfunc/_kubectl
helm completion zsh >$HOME/.zfunc/_helm
