#!/bin/bash

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME/nixpkgs"
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME/nixpkgs/config.nix"

# Download .zshrc from main dotfiles repo
curl -o "$HOME/.zshrc" https://raw.githubusercontent.com/Lucioschenkel/dotfiles/main/.zshrc

# arch=$(file -Lb /usr/bin/ld | cut -d, -f2)

# echo "Arch: $arch"

# Use nix for arm64, linuxbrew on amd64
# if [[ "$arch" == x86* ]]; then
#   # Setup homebrew
#   test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
#   test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
#
#   # Install brew packages
#   packages=(
#     direnv
#     fd
#     fluxcd/tap/flux
#     fzf
#     kubectl
#     kubectx
#     k9s
#     lazygit
#     npm
#     ripgrep
#     stow
#   )
#   for package in "${packages[@]}"; do
#     /home/linuxbrew/.linuxbrew/bin/brew install "$package"
#   done
#
# else
# Install packages from config.nix
nix-env -iA nixpkgs.myPackages
# fi

# Install pure prompt
mkdir -p "$HOME/.zsh"
git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"

# Symlink dotfiles
stow .

# Setup shell completion
mkdir -p "$HOME/.zfunc"
flux completion zsh >$HOME/.zfunc/_flux
kubectl completion zsh >$HOME/.zfunc/_kubectl
helm completion zsh >$HOME/.zfunc/_helm
